project_name: commander
builds:
  - main: ./cmd/commander/main.go
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  -
    files:
      - "example.env"